# Generated by Django 4.2.5 on 2023-09-27 19:52

from django.db import migrations, models
import django.db.models.deletion
import image.utils
import image.validators
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expiringlink",
            name="expiry_time",
        ),
        migrations.AddField(
            model_name="expiringlink",
            name="expires_in",
            field=models.IntegerField(default=0, validators=[image.validators.validate_expiration_time]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expiringlink",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="expiringlink",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="expiring_link", to="images.image"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                upload_to=image.utils.image_upload_path,
                validators=[image.validators.validate_image_extension],
            ),
        ),
    ]